services:
  # --- Banco de Dados ---
  db:
    image: postgres:15-alpine
    container_name: iw_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - iw_network

  # --- Cache ---
  redis:
    image: redis:7-alpine
    container_name: iw_redis
    ports:
      - "6379:6379"
    networks:
      - iw_network

  # --- Backend (Django) ---
  backend:
    build: ./backend
    container_name: iw_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - media_data:/app/media
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - iw_network

  # --- Frontend (Vue.js) ---
  frontend:
    build: ./frontend
    container_name: iw_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules # Mantém os módulos do build protegidos
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - iw_network

  # --- Gateway (Nginx) ---
  nginx:
    image: nginx:1.25-alpine
    container_name: iw_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - media_data:/app/media:ro
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
    networks:
      - iw_network
  
  celery_worker:
    build: ./backend
    container_name: iw_celery
    command: celery -A config worker --loglevel=info
    volumes:
      - ./backend:/app
      - media_data:/app/media
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - REDIS_HOST=redis://iw_redis:6379/0
    depends_on:
      - db
      - redis
      - backend
    networks:
      - iw_network

volumes:
  postgres_data:
  media_data:

networks:
  iw_network:
    driver: bridge

